sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
script: mvn clean verify
after_success:
  - docker build -t jomoespe/zoopluschallenge .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull jomoespe/zoopluschallenge
